/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package careercounseling;

/**
 *
 * @author dvp
 */
public class Tenth extends javax.swing.JFrame {

    /**
     * Creates new form Tenth
     */
    public Tenth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea28 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("                               BOARDS AVAILABLE IN INDIA\n\nThere are four main education boards available in India. Students may choose a stream that suits \nthem best.The choice shall be made on the basis of difficulty level associated with the boards and aptitude of the\n student. The names of the boards are-\n\n1. CBSE (Central Board of Secondary Education)\n2. ICSE (Indian Certificate of Secondary Education)3,\n3. IB (International Baccalaureate)\n4. State Boards\n \n\nIB is the toughest board among the above mentioned entries. It focuses on the concept of ‘how to\nlearn’.Much emphasis is laid on ‘application of knowledge’ and ‘practical aspects’ of learning.\n\nIB board is followed by ICSE board, when it comes to difficulty level. Then comes CBSE board. I \nthink most of you are knowledgeable about this board. It functions under the Union Government of \nIndia. Difficulty level associated with this board is moderate.\n\nLast comes State Boards. Each State in India has its own education board. It functions under the\n respective State Governments of each state. Language of instruction (medium) in case of schools\n affiliated to such boards are- regional language and English.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 810, 370));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane1.addTab("Boards", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);
        jTextArea5.setText("                 \n                    Benefits and advantages of choosing Science stream\n\n\n1.The technological development and the innovations is a new hallmark of the world today. The science\n  stream will give you more opportunities to prosper.\n\n2.Science stream lets you become Smarter, progressive and intelligent.\n\n3.As you invariably study the subjects like Physics and Chemistry you will develop the\n  scientific knowledge and theory and the understanding of the world with the causes and \n  effects.\n\n4.Science has the potential of remarkable and progressive developments on many fronts  \n  which create infinite possibilities. You obviously become the part of this ever-growing\n  chain of development.\n\n5.You will get much more opportunities to learn new things right from Human body to space to \n  universe.\n\n6.Science is all about discoveries which make you think creatively and lets posses the\n  excellent problem-solving skills.\n\n7.You get the knowledge which will be applicable in literally every field that will make\n  you secure in terms of career, practical life.\n\n8.You can pursue your higher education from world class institutions in India like IITs,\n  NITs.\n");
        jScrollPane5.setViewportView(jTextArea5);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 740, 380));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 430));

        jTabbedPane1.addTab("Science", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea18.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea18.setRows(5);
        jTextArea18.setText("\n                  Benefits and advantages of choosing Commerce stream\n\n The career in Commerce and Economic field is the opportunity to become the part of the\n businesses at its core because without finance there nothing will happen and you will\n be at the helm to \n manage it.\n1.The Economics as one of the subject in this stream consists of the relation between \n  production,distribution, and consumption of goods and services. You come to know how\n  the Economies the world over run.\n\n2.In the Business Study subject, you will essentially learn the operations of the \n  organization and modern business enterprises.\n\n3.In Accountancy, which contains some form of mathematics is actually related to the \n  financial information about a business entity\n\n\n");
        jScrollPane18.setViewportView(jTextArea18);

        jPanel3.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 730, 380));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel5");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 430));

        jTabbedPane1.addTab("Commerce", jPanel3);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea19.setColumns(20);
        jTextArea19.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea19.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea19.setRows(5);
        jTextArea19.setText("\n                   Benefits and advantages of choosing Arts stream\n\n\n  Studying Arts or Humanities help a student develop powers of analysis and expression.\n\n1.Though the study of arts may not make you directly employable, it prepares you for \n  future jobs that require good communication skills, logical reasoning and analytical \n  ability.\n\n2.Many employers prefer people from Humanities background because not only do they have\n  the ability to work independently and analytically but they are also experts in \n  collecting information and writing clearly and coherently.\n\n3.The plethora of subjects that a student gets to study under Humanities stream is huge. Subjects \n  like Geography, Philosophy, History, Sociology, and Political Science open a wide \n  variety of career options.");
        jScrollPane19.setViewportView(jTextArea19);

        jPanel6.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 710, 390));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel5");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 430));

        jTabbedPane1.addTab("Arts", jPanel6);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setRows(5);
        jTextArea6.setText("          Art Teacher Diploma\n\nIt is typically a 2-year program to train\ncandidates in the fundamental principles \nof visual and design experience\n\nJob Scope: : Arts Teacher");
        jScrollPane6.setViewportView(jTextArea6);

        jPanel10.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 59, 357, 275));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel8.setText("jLabel5");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 840, 450));

        jTabbedPane3.addTab("Arts Teacher", jPanel10);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea7.setRows(5);
        jTextArea7.setText("       Commercial Art Diploma\n\nCommercial art, often called advertising\nart, helps understand nuance of selling \ngoods and services. It is completely \ndifferent from fine art.\n\nJob Scope: Art studios, Advertising \n           companies, Publishing houses,\n           Fashion houses\n\nRelevant Courses:Lateral entry BFA, MFA\n");
        jScrollPane7.setViewportView(jTextArea7);

        jPanel12.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 330, 260));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel25.setText("jLabel5");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 390));

        jTabbedPane3.addTab("Commercial Arts", jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea8.setRows(5);
        jTextArea8.setText("Diploma in Beauty culture & Hair dressing\n\nBeauty Care courses,ranging from 3 months\nto a year,impart training in body care.\nJob profile generally begins with \ntrainee in beauty salons.\n\nJob Scope: Self Beauty saloon & Beauty \n           Expert");
        jScrollPane8.setViewportView(jTextArea8);

        jPanel13.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 340, 270));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel24.setText("jLabel5");
        jPanel13.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 840, 450));

        jTabbedPane3.addTab("Beauty culture & Hair dressing", jPanel13);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea9.setRows(5);
        jTextArea9.setText("      Diploma in Garment technology\n\nGarment Technology is a 3-year diploma\ncourse which equips candidates with \ntechniques of timely delivery of merchandise\n& optimal resource utilization.\n\nJob Scope: Self Boutique & Fashion designer\n");
        jScrollPane9.setViewportView(jTextArea9);

        jPanel14.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 357, 275));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel23.setText("jLabel5");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 826, 380));

        jTabbedPane3.addTab("Garment technology", jPanel14);

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea10.setRows(5);
        jTextArea10.setText("           Diploma in Stenography\n\nIt is a one-year diploma in administrative\nvocational trade where candidates are \nequipped in taking short-hand dictations\nand perform clerical duties.\n\nJob Scope: Secretary, Stenographer,Computer\n           Operator, Clerk-cum-Typist in \n           Private and Govt. sector");
        jScrollPane10.setViewportView(jTextArea10);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel22.setText("jLabel5");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane3.addTab("Stenography ", jPanel15);

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea11.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea11.setRows(5);
        jTextArea11.setText("          Engineering Diploma\n\nIt is a technical degree below the \nundergraduate rank which aims to enable \nstudents to understand technical \ncommunication and apply basic problem \nsolving techniques.\n\nJob Scope: Govt. Contractor\n\nRelevant Courses: Degree Engineering, \n                 Associate membership of \n                 institute of engineers");
        jScrollPane11.setViewportView(jTextArea11);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel21.setText("jLabel5");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane3.addTab("Engineering Diploma", jPanel16);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea12.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea12.setRows(5);
        jTextArea12.setText("    Industrial Training Institutes\n\nIndustrial Training Institutes (ITIs) are\ngovernment-run training organizations \nwhich offer post-school technical \ntraining ranging from 6 months to 2 years\nin varied fields.\n\nJob Scope: Apprentice, welder & Govt. \n           jobs");
        jScrollPane12.setViewportView(jTextArea12);

        jPanel17.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 340, 275));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel20.setText("jLabel5");
        jPanel17.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 390));

        jTabbedPane3.addTab("Industrial Training Institutes", jPanel17);

        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea28.setEditable(false);
        jTextArea28.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea28.setColumns(20);
        jTextArea28.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea28.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea28.setRows(5);
        jTextArea28.setText("     Laboratory Technician Diploma\n\nThis course is meant for training in\nClinical Laboratory technology where \nstudents are equipped with technical \nknow-how for placement in clinical labs\n& hospitals. Though duration varies, it\nis mostly a 3-year course.\n\nJob Scope: Lab Technician, Lab Assistant,\n           Self employment");
        jScrollPane28.setViewportView(jTextArea28);

        jPanel33.add(jScrollPane28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 340, 250));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel31.setText("jLabel5");
        jPanel33.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 830, 370));

        jTabbedPane3.addTab("Laboratory Technician", jPanel33);

        jPanel5.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 430));

        jTabbedPane1.addTab("Diploma", jPanel5);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea17.setEditable(false);
        jTextArea17.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea17.setColumns(20);
        jTextArea17.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea17.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea17.setRows(5);
        jTextArea17.setText("          Data Entry operators\n\nGenerally, data entry jobs do not \nrequire any specific educational \nrequirements except for a high speed and \naccurate typing proficiency.");
        jScrollPane17.setViewportView(jTextArea17);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel26.setText("jLabel5");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane7.addTab("Data Entry operators", jPanel21);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea16.setEditable(false);
        jTextArea16.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea16.setColumns(20);
        jTextArea16.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea16.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea16.setRows(5);
        jTextArea16.setText("           Enrolled Follower\n\nIndian Coast guard offers opportunities\nto individuals for employment as enrolled\nfollower with the job profile of cleaning\nCoast Guard buildings, offices and ships\netc.");
        jScrollPane16.setViewportView(jTextArea16);

        jPanel22.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 340, 250));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel27.setText("jLabel5");
        jPanel22.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 430));

        jTabbedPane7.addTab("Enrolled Follower", jPanel22);

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea15.setEditable(false);
        jTextArea15.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea15.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea15.setRows(5);
        jTextArea15.setText("             LIC Agents\n\nLIC agents are professionals who work\nat ground level for the Life Insurance\nCorporation of India. They are actually\nintermediaries who create ties between\nLIC clients and LIC.");
        jScrollPane15.setViewportView(jTextArea15);

        jPanel25.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 320, 250));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel28.setText("jLabel5");
        jPanel25.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 430));

        jTabbedPane7.addTab("LIC Agents", jPanel25);

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea14.setEditable(false);
        jTextArea14.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea14.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea14.setRows(5);
        jTextArea14.setText("           Police Constable\n\nPolice department of different states\noffer jobs for Constable and recruits \ncandidates on basis of their performance\nin preliminary exam,main exam,physical \ntest & medical test.");
        jScrollPane14.setViewportView(jTextArea14);

        jPanel26.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 330, 260));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel29.setText("jLabel5");
        jPanel26.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 430));

        jTabbedPane7.addTab("Police Constable", jPanel26);

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea13.setEditable(false);
        jTextArea13.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea13.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea13.setRows(5);
        jTextArea13.setText("                  Sailor\n\nIndian Navy recruits sailors for their \nmaritime operations. The selection process \nincludeshour-long objective test, physical \nfitness test & medical test. Selected \ncandidates are put on probation for 2 years.");
        jScrollPane13.setViewportView(jTextArea13);

        jPanel27.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 360, 260));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel30.setText("jLabel5");
        jPanel27.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 820, 410));

        jTabbedPane7.addTab("Sailor", jPanel27);

        jPanel7.add(jTabbedPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 430));

        jTabbedPane1.addTab("Become Professional", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 450));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Homepage");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Sign Out");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel32.setText("jLabel5");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 830, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         Mainpage hm=new Mainpage();
         hm.setVisible(true);
         this.dispose();

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
      Homepage mp=new Homepage();
      mp.setVisible(true);
      this.dispose();  
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tenth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tenth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tenth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tenth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tenth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
