/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package careercounseling;

/**
 *
 * @author dvp
 */
public class Twelfth extends javax.swing.JFrame {

    /**
     * Creates new form Tenth
     */
    public Twelfth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel28 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea25 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jScrollPane36 = new javax.swing.JScrollPane();
        jTextArea36 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jScrollPane37 = new javax.swing.JScrollPane();
        jTextArea37 = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jScrollPane38 = new javax.swing.JScrollPane();
        jTextArea38 = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel33 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea26 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jScrollPane35 = new javax.swing.JScrollPane();
        jTextArea35 = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane34 = new javax.swing.JScrollPane();
        jTextArea34 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jScrollPane33 = new javax.swing.JScrollPane();
        jTextArea33 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTextArea32 = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        jScrollPane39 = new javax.swing.JScrollPane();
        jTextArea39 = new javax.swing.JTextArea();
        jLabel39 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel38 = new javax.swing.JPanel();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTextArea31 = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextArea29 = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Chartered Accountant\n\nA chartered accountant, accredited by the Institute of \nChartered Accountants of India, deals with financial aspects \nof business such as auditing & taxation.\n\nJob Scope: Private Practice, Financial Advisor\n\nRelevant Courses: Master of Business Administration\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Chartered Accountant", jPanel13);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Cost & Management Accountants\n\nCost & Management Accountants are governed by Institute of \nCost Accountants of India. They are trained in subject \nareas such as management accounting, corporate laws, \ntaxation, cost accounting etc.\n\nJob Scope: Cost Accountant, Management Accountant\n\nRelevant Courses: Certifications, Master of Business \n                  Administration\n");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel15.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 480, 310));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane3.addTab("Cost & Management Accountants", jPanel15);

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea4.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jTextArea4.setText("Bachelor of Commerce\n\nA Bachelor of Commerce is a three year undergraduate degree programme in business and commerce. It also equips candidate with basic understating of related subjects such as economics, marketing, statistics etc.\n\nJob Scope: Account Executive, Financial Analyst\n\nRelevant Courses: :Master of Commerce, Master of Business Administration\n");
        jScrollPane4.setViewportView(jTextArea4);

        jPanel16.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 480, 290));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel16.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane3.addTab("Bachelor of Commerce", jPanel16);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea5.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);
        jTextArea5.setText("Bachelor of Business Administration\n\nBachelor of Business Administration is a three years \nbachelor's degree in management and includes both general \nbusiness courses as well as advanced courses in different \nspecializations.\n\nJob Scope: Business Development Executive, Office Operations\n\nRelevant Courses: Master of Business Administration\n");
        jScrollPane5.setViewportView(jTextArea5);

        jPanel17.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 490, 270));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel1");
        jPanel17.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 380));

        jTabbedPane3.addTab("Bachelor of Business Administration", jPanel17);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Company Secretary\n\nEquipped with full knowledge of corporate laws, capital\nmarkets, and corporate governance,\nCompany Secretary in a company ensures all regulatory \ncompliances in short, medium and long-term \nfunctioning.\n\nJob Scope: Investment Banker, Stock Exchanges, Compliance \nOfficer, Corporate Planner\n\nRelevant Courses: Bachelor of Law, Master of Business \nAdministration\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 470, 290));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 390));

        jTabbedPane3.addTab("Company Secretary", jPanel14);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Commerce", jPanel2);

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea11.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea11.setRows(5);
        jTextArea11.setText("                 B.Sc. in Hospitality and Hotel Administration\n\nIt is a 3-year degree programme affiliated by National Council for Hotel Management \n& Catering Technology (NCHMCT). Admission is conducted through an All India Joint Entrance \nExam- NCHMJEE.\n\nJob Scope:\n• Management Trainee in Hotel & hospitality.\n• Kitchen Management/Housekeeping positions in Hotels.\n• Flight Kitchens & on-board flight services\n• Indian Navy Hospitality services\n");
        jScrollPane11.setViewportView(jTextArea11);

        jPanel18.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 770, 250));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel20.setText("jLabel1");
        jPanel18.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane4.addTab("B.Sc. in Hospitality and Hotel Administration", jPanel18);

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea12.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea12.setRows(5);
        jTextArea12.setText("               Diploma in Dance & Music\n\nDiploma courses in varied dance forms and music genres as\nwell as instruments can be pursued by candidate for hobby\nor as a professional programme.\n\nJob Scope: Choreographers, Dance Teacher, Performing \n           Artist\n");
        jScrollPane12.setViewportView(jTextArea12);

        jPanel19.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 470, 250));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel11.setText("jLabel1");
        jPanel19.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane4.addTab("Diploma in Dance & Music", jPanel19);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea13.setEditable(false);
        jTextArea13.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea13.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea13.setRows(5);
        jTextArea13.setText("         Diploma in Elementary Education\n\nIt is a one-year diploma in administrative vocational \ntrade where candidates are equipped in taking short-\nhand dictations and perform clerical duties.\n\nJob Scope: Elementary school teacher and Nursery \n           school teacher\n");
        jScrollPane13.setViewportView(jTextArea13);

        jPanel20.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 440, 230));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel12.setText("jLabel1");
        jPanel20.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane4.addTab("Diploma in Elementary Education", jPanel20);

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea14.setEditable(false);
        jTextArea14.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea14.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea14.setRows(5);
        jTextArea14.setText("         Diploma in travel and tourism\n\nOne year diploma course offering management training\nin entry level jobs in hotels, airports, travel \ncompanies/agencies, cruise liners and online travel \nbooking websites.\n\nJob Scope: Job opportunities in hotels, Quick Service\n           Restaurant (QSR)\n");
        jScrollPane14.setViewportView(jTextArea14);

        jPanel21.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 430, 270));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel13.setText("jLabel1");
        jPanel21.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 370));

        jTabbedPane4.addTab("Diploma in travel and tourism", jPanel21);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea15.setEditable(false);
        jTextArea15.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea15.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea15.setRows(5);
        jTextArea15.setText("L.L.B (Hons) Integrated Course\n\nThis is a 5-year integrated law course where candidates can \nchoose a Law programme aligned with their core stream - B.A.\nLL.B (Hons.) , B.B.A. LL.B (Hons.) , B.Sc. LL.B (Hons.) , B.Com.\nLL.B (Hons.) and , B.S.W. LL.B (Hons.)\n\nJob Scope: Legal Advisor, Legal Practitioner and Advocate\n\nRelevant Courses: L.L.M , M. Phil. , Ph.D , Post Graduate Law \n                  Diploma, Post Graduate Law Diploma, Master of \nPublic Policy,Post Graduate Diploma in Labour Law (D.L.L.)\n");
        jScrollPane15.setViewportView(jTextArea15);

        jPanel22.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 520, 280));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel14.setText("jLabel1");
        jPanel22.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 370));

        jTabbedPane4.addTab("L.L.B (Hons) Integrated Course", jPanel22);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Specialization", jPanel3);

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea16.setEditable(false);
        jTextArea16.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea16.setColumns(20);
        jTextArea16.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea16.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea16.setRows(5);
        jTextArea16.setText("Interior designer\n\nCandidate can choose from multitude of specializations based on talent & interest, \nsuch as furniture design, healthcare design, hospitality design, retail design, \nworkspace design etc\n");
        jScrollPane16.setViewportView(jTextArea16);

        jPanel23.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 670, 170));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel17.setText("jLabel1");
        jPanel23.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 380));

        jTabbedPane5.addTab("Interior designer", jPanel23);

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea17.setEditable(false);
        jTextArea17.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea17.setColumns(20);
        jTextArea17.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea17.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea17.setRows(5);
        jTextArea17.setText("Secretarial Practice\n\nIt is a one-year diploma which enables a candidate to be self -employed, offer contractual\nservices to organizations or be employed as office assistant\n");
        jScrollPane17.setViewportView(jTextArea17);

        jPanel24.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 730, 190));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel16.setText("jLabel1");
        jPanel24.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane5.addTab("Secretarial Practice", jPanel24);

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea18.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea18.setRows(5);
        jTextArea18.setText("Customer Service Operator\n\nVaried skills are required based on the project & type of the businesses but primarily \ngood command over language, computer literacy & communication skills are essential.\n");
        jScrollPane18.setViewportView(jTextArea18);

        jPanel25.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 710, 160));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel18.setText("jLabel1");
        jPanel25.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 380));

        jTabbedPane5.addTab("Customer Service Operator", jPanel25);

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea19.setColumns(20);
        jTextArea19.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea19.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea19.setRows(5);
        jTextArea19.setText("Commercial Pilot License\n\nCommercial Pilot Training for the pilot's License Conversion Examination\nis conducted by DGCA, Govt. of India post completion of 200 hours of \nflight time.\n");
        jScrollPane19.setViewportView(jTextArea19);

        jPanel26.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 590, 160));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel19.setText("jLabel1");
        jPanel26.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane5.addTab("Commercial Pilot License", jPanel26);

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea20.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea20.setRows(5);
        jTextArea20.setText("Air hostess/Steward\n\nThis job basically has a profile of flight attendants. Candidates are selected basis written \ntest & interviews. Preference is given to candidates with fluency in English & knowledge of \npopular foreign languages.\n");
        jScrollPane20.setViewportView(jTextArea20);

        jPanel27.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 750, 160));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel15.setText("jLabel1");
        jPanel27.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 390));

        jTabbedPane5.addTab("Air hostess/Steward", jPanel27);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Become Professional", jPanel4);

        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea22.setEditable(false);
        jTextArea22.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea22.setColumns(20);
        jTextArea22.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea22.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea22.setRows(5);
        jTextArea22.setText("Bachelor of Ayurveda, Medicine & Surgery \n(B.A.M.S.)\n\nIt is a five-and-a-half-year undergraduate\ndegree course that also includes one year\nof internship. After successful completion\nof the course, students are designated as\nAyurvedacharya doctor.\n\nJob Scope: Ayurveda Consultation, General\n           Practice, Clinical Research\n\nRelevant Courses: Master of Public Health,\n                  PG Diploma\n");
        jScrollPane22.setViewportView(jTextArea22);

        jPanel28.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 350, 280));

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel25.setText("jLabel1");
        jPanel28.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("(B.A.M.S.)", jPanel28);

        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea21.setEditable(false);
        jTextArea21.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea21.setColumns(20);
        jTextArea21.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea21.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea21.setRows(5);
        jTextArea21.setText("Bachelor of Dental Surgery (B. D. S.)\n\nIt is 5-year degree course, which includes\n4 years of study followed by one year of\ninternship. After successful completion\nof this degree programme, candidate is\ndesignated as Dentist.\n\nJob Scope: Lecturer, General Practice\n\nRelevant Courses: Master of Dental Surgery, \n                  Master of Public Health\n");
        jScrollPane21.setViewportView(jTextArea21);

        jPanel29.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 350, 260));

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel24.setText("jLabel1");
        jPanel29.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("(B. D.S.)", jPanel29);

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea23.setEditable(false);
        jTextArea23.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea23.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea23.setRows(5);
        jTextArea23.setText("Bachelor of Homeopathic Medicine & Surgery\n(B.H.M.S.)\n\nBHMS is an undergraduate degree course of\nfive-and-a-half-year duration (including \none year compulsory internship). After \nsuccessful completion of the course, \nstudents are designated as Homeopathic \ndoctor.\n\nJob Scope: Homeopathy Consultation, \n           General Practice, Clinical \nResearch\n\nRelevant Courses: Doctor of Medicine in \n                 Homeopathy, PG Diploma\n");
        jScrollPane23.setViewportView(jTextArea23);

        jPanel30.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 360, 290));

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel23.setText("jLabel1");
        jPanel30.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("B.H.M.S", jPanel30);

        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea24.setEditable(false);
        jTextArea24.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea24.setColumns(20);
        jTextArea24.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea24.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea24.setRows(5);
        jTextArea24.setText("Bachelor of Medicine & Surgery (M.B.B.S)\n\nMBBS is a five-and-a-half-year degree course\nwhich includes one year of mandatory internship in\na hospital attached or approved by the concerned \nmedical college. After successful completion of \nthe course, students can practice Medicine & \nSurgery.\n\nJob Scope: Doctor, General Clinical Practice, \n           Research\nRelevant Courses: Doctor of Medicine(MD), Master \n                  of surgery (MS)\n");
        jScrollPane24.setViewportView(jTextArea24);

        jPanel31.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 410, 330));

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel22.setText("jLabel1");
        jPanel31.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("(M.B.B.S)", jPanel31);

        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea25.setEditable(false);
        jTextArea25.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea25.setColumns(20);
        jTextArea25.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea25.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea25.setRows(5);
        jTextArea25.setText("Bachelor of Science \n\nBachelor of Science is three-year degree \nprogramme offered in multitude of \nspecializations under the pure sciences domain\nsuch as Maths, Physics, Chemistry, Botany, \nZoology etc.\n\nJob Scope: BPO, SSC Exams, Graduate level \n           exams\n\nRelevant Courses: MSc,MA\n");
        jScrollPane25.setViewportView(jTextArea25);

        jPanel32.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 380, 300));

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel21.setText("jLabel1");
        jPanel32.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("Bachelor of Science ", jPanel32);

        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea36.setEditable(false);
        jTextArea36.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea36.setColumns(20);
        jTextArea36.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea36.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea36.setRows(5);
        jTextArea36.setText("Bachelor of Science Nursing \n\nBachelor of Science in Nursing is a four-\nyear programme which involves classroom \nlessons, practical sessions as well as \nclinical work apart from internship.\n\nJob Scope: Employment in Hospitals & \n           Clinics, Training institutes\n\nRelevant Courses: MSc Nursing, Post \n                  Graduate Program in \nPublic Health Management (PGPPHM)\n");
        jScrollPane36.setViewportView(jTextArea36);

        jPanel43.add(jScrollPane36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 350, 280));

        jLabel36.setBackground(new java.awt.Color(102, 102, 102));
        jLabel36.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel36.setText("jLabel1");
        jPanel43.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("Bachelor of Science Nursing ", jPanel43);

        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea37.setEditable(false);
        jTextArea37.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea37.setColumns(20);
        jTextArea37.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea37.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea37.setRows(5);
        jTextArea37.setText("Bachelor of Veterinary Science & Animal\nHusbandry (B. V. Sc. & AH)\n\nThis is a five year undergraduate degree \ncourse with 6 months mandatory internship \nwhich includes training in practicing & \nteaching Veterinary science and livestock \n& poultry farm management.\n\nJob Scope: Veterinary Clinics, Zoos & Wild \n          life Research organizations\nRelevant Courses: Master of Veterinary \n                  Science, PhD \n(Veterinary and Animal Sciences)\n");
        jScrollPane37.setViewportView(jTextArea37);

        jPanel44.add(jScrollPane37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 360, 280));

        jLabel37.setBackground(new java.awt.Color(102, 102, 102));
        jLabel37.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel37.setText("jLabel1");
        jPanel44.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("(B. V. Sc. & AH)", jPanel44);

        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea38.setEditable(false);
        jTextArea38.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea38.setColumns(20);
        jTextArea38.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea38.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea38.setRows(5);
        jTextArea38.setText("Pharmacist\nAfter completing the Bachelor of Pharmacy, one can choose to become health-system \npharmacist or a community pharmacist or hospital pharmacist.\n\nPhysiotherapist \nDiploma in Physiotherapy (DPT) is a two-year professional training course which enables\ncandidates to practice in fitness center, hospitals & clinics.\n\nSales Representative\nCandidates who are outgoing are apt to start career as sales representative in \norganizations operating in healthcare, cosmetics & beauty care segment.\n");
        jScrollPane38.setViewportView(jTextArea38);

        jPanel45.add(jScrollPane38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 720, 280));

        jLabel38.setBackground(new java.awt.Color(102, 102, 102));
        jLabel38.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel38.setText("jLabel1");
        jPanel45.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane6.addTab("Become Professional", jPanel45);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Science(PCB)", jPanel5);

        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea26.setEditable(false);
        jTextArea26.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea26.setColumns(20);
        jTextArea26.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea26.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea26.setRows(5);
        jTextArea26.setText("Bachelor of Architecture (B. Arch.)\n\nThe Bachelor of Architecture (B.Arch.), recognized by \nCouncil of Architecture (COA), is 5-year degree \nprogramme including a period of practical training prior\nto professional examination and registration.\n\nJob Scope: Design Architect, Project Architect, Interior\n           Architect\nRelevant Courses: Master in Architecture (M Arch), MBA\n\n");
        jScrollPane26.setViewportView(jTextArea26);

        jPanel33.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 460, 300));

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel26.setText("jLabel1");
        jPanel33.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane7.addTab("Bachelor of Architecture (B. Arch.)", jPanel33);

        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea35.setEditable(false);
        jTextArea35.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea35.setColumns(20);
        jTextArea35.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea35.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea35.setRows(5);
        jTextArea35.setText("Bachelor of Computer Applications (BCA)\n\nBachelor of Computer Applications is an undergraduate \ndegree course of three years which equips candidate with \nskills to analyze& synthesize computer systems, \napplications & information systems.\n\nJob Scope: Programmer, Networking Professional\n\nRelevant Courses: MCA, MCM, B. Ed.\n");
        jScrollPane35.setViewportView(jTextArea35);

        jPanel34.add(jScrollPane35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 480, 280));

        jLabel35.setBackground(new java.awt.Color(102, 102, 102));
        jLabel35.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel35.setText("jLabel1");
        jPanel34.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane7.addTab("Bachelor of Computer Applications (BCA)", jPanel34);

        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea34.setEditable(false);
        jTextArea34.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea34.setColumns(20);
        jTextArea34.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea34.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea34.setRows(5);
        jTextArea34.setText("Bachelor of Engineering (BE/B Tech)\n\nBE/B Tech is a four-year engineering degree programme approved\nby AICTE in specific branchs such as Civil, Mechanical, \nElectrical, Information Technology etc.\n\nJob Scope:IT Professional, Government Contractors\n\nRelevant Courses: ME/M Tech, MS, MBA\n");
        jScrollPane34.setViewportView(jTextArea34);

        jPanel35.add(jScrollPane34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 510, 270));

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel27.setText("jLabel1");
        jPanel35.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane7.addTab("Bachelor of Engineering (BE/B Tech)", jPanel35);

        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea33.setEditable(false);
        jTextArea33.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea33.setColumns(20);
        jTextArea33.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea33.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea33.setRows(5);
        jTextArea33.setText("Bachelor of Planning\n\nBachelor of planning is a professional four-year \ntechnical degree programme which prepares candidates \nwith adequate skills for infrastructure planning in \ndifferent capacities.\n\nJob Scope: Professional Planner, Architectural Firms\n\nRelevant Courses: Master of Planning\n");
        jScrollPane33.setViewportView(jTextArea33);

        jPanel36.add(jScrollPane33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 460, 280));

        jLabel28.setBackground(new java.awt.Color(102, 102, 102));
        jLabel28.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel28.setText("jLabel1");
        jPanel36.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane7.addTab("Bachelor of Planning", jPanel36);

        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea32.setEditable(false);
        jTextArea32.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea32.setColumns(20);
        jTextArea32.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea32.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea32.setRows(5);
        jTextArea32.setText("Bachelor of Science\n\nBachelor of Science is three-year degree programme \noffered in multitude of specializations under the pure \nsciences domain such as Maths, Physics, Chemistry, \nBotany, Zoology etc.\n\nJob Scope: Graduate level Exams, BPO, SSC Exams\n\nRelevant Courses: MSc, MA\n");
        jScrollPane32.setViewportView(jTextArea32);

        jPanel37.add(jScrollPane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 450, 290));

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel29.setText("jLabel1");
        jPanel37.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane7.addTab("Bachelor of Science", jPanel37);

        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea39.setEditable(false);
        jTextArea39.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea39.setColumns(20);
        jTextArea39.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea39.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea39.setRows(5);
        jTextArea39.setText("Cinematographer\nCandidates interested in careers as Cinematographer can pursue diploma course which\nenables them to operate technical devices and understand props towards getting \nperfect shots.\n\nDeck Cadet – Merchant Navy\nCandidate with minimum 60 per cent aggregate marks in PCM in class 12th can pursue \na one-year residential diploma in Nautical Science course approved by Directorate \nGeneral of Shipping.\n\nTechnical Entry - Indian Army\nCandidate with minimum 70 per cent aggregate marks in PCM in class 12th can pursue\ntechnical entry scheme. After successful selection in the SSB Interview, one is \nemployed under permanent commission in the Army.\n\n");
        jScrollPane39.setViewportView(jTextArea39);

        jPanel46.add(jScrollPane39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 690, 280));

        jLabel39.setBackground(new java.awt.Color(102, 102, 102));
        jLabel39.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel39.setText("jLabel1");
        jPanel46.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane7.addTab("Become Professional", jPanel46);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Science(PCM)", jPanel6);

        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea31.setEditable(false);
        jTextArea31.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea31.setColumns(20);
        jTextArea31.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea31.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea31.setRows(5);
        jTextArea31.setText("Bachelor of Science in Dairy Technology (B. Sc. \nDairy Technology)\n\nIt is a 4-year undergraduate agriculture science \nand technology course which deals with processing \nmilk & other allied products.\nJob Scope: Quality Control Analyst in dairy \n           processing plants\nRelevant Courses: Master of Science in Dairy \n                  Technology\n");
        jScrollPane31.setViewportView(jTextArea31);

        jPanel38.add(jScrollPane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 420, 280));

        jLabel30.setBackground(new java.awt.Color(102, 102, 102));
        jLabel30.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel30.setText("jLabel1");
        jPanel38.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane8.addTab("(B. Sc.  Dairy Technology)", jPanel38);

        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea30.setEditable(false);
        jTextArea30.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea30.setColumns(20);
        jTextArea30.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea30.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea30.setRows(5);
        jTextArea30.setText("B. Tech. in Agriculture\n\nBachelor of Technology in Agriculture Engineering\nis a 4-year programme which deals with the study\nof breeding plants which are consumed by\nhuman beings and livestock.\n\nJob Scope: Teaching, Farm Manager, Researcher\n\nRelevant Courses: Master of Technology in \n                 Agriculture Students having PCMB\nprofile can opt any course and job from PCM as \nwell as PCB sections.\n");
        jScrollPane30.setViewportView(jTextArea30);

        jPanel39.add(jScrollPane30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 400, 280));

        jLabel31.setBackground(new java.awt.Color(102, 102, 102));
        jLabel31.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel31.setText("jLabel1");
        jPanel39.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane8.addTab("B. Tech. in Agriculture", jPanel39);

        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea29.setEditable(false);
        jTextArea29.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea29.setColumns(20);
        jTextArea29.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea29.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea29.setRows(5);
        jTextArea29.setText("Horticulturist\nA diploma in agriculture prepares one to be a Horticulturist. The professionals deal\nwith cultivation of flowers, plants, fruits, vegetables and also maintaining \nnurseries, landscaping gardens etc.\n\nMedical Technologist\nThey are professionals such as optometrist & Radiographers who carry out the \nnecessary tests advised by the medical practitioner & report their findings back.\n\nOperation Theatre Technician\nOT technician basically assist surgeons in performing operations with key \nresponsibilities involving preparation for operation, maintenance as well as safety \nof the instruments\n");
        jScrollPane29.setViewportView(jTextArea29);

        jPanel40.add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 680, 280));

        jLabel32.setBackground(new java.awt.Color(102, 102, 102));
        jLabel32.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel32.setText("jLabel1");
        jPanel40.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 380));

        jTabbedPane8.addTab("Become Professional", jPanel40);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Scienece(PCMB)", jPanel9);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setRows(5);
        jTextArea6.setText("Bachelor of Business Administration\n\nBachelor of Business Administration is a three years \nbachelor's degree in management and includes both general\nbusiness courses as well as advanced courses in different\nspecializations.\n\nJob Scope: Marketing Executive, Business Development \n           Executive.\n\nRelevant Courses: Master of Business Administration\n");
        jScrollPane6.setViewportView(jTextArea6);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 470, 300));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel10.setText("jLabel1");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 360));

        jTabbedPane2.addTab("Bachelor of Business Administration", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea7.setRows(5);
        jTextArea7.setText("Bachelor of Arts\n\nA Bachelor of Arts is a broad interdisciplinary \nundergraduate degree program encompassing general \neducation, electives and major area of study courses \nlike History, Psychology, Geography, Public \nAdministration, Literature etc.\n\nJob Scope: Teacher, Content Writer, Customer Support \n           Executive\n\nRelevant Courses: B.ED , M.A , MBA\n");
        jScrollPane7.setViewportView(jTextArea7);

        jPanel8.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 440, 310));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel7.setText("jLabel1");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane2.addTab("Bachelor of Arts", jPanel8);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea8.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea8.setRows(5);
        jTextArea8.setText("Bachelor of Social Work\n\nBachelor of Social Work is a 3-year degree course which \nequips candidates with knowledge and skills required to \nperform social services through NGOs, CSR activities or \nindependently.\n\nJob Scope: Social worker, counsellor, NGO sector\n\nRelevant Courses: MSW, MA (Social)\n");
        jScrollPane8.setViewportView(jTextArea8);

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 480, 290));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel8.setText("jLabel1");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane2.addTab("Bachelor of Social Work", jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea9.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea9.setRows(5);
        jTextArea9.setText("Bachelor of Architecture\n\nThe Bachelor of Architecture (B.Arch.), recognized\nby Council of Architecture (COA), is 5-year degree \nprogramme including a period of practical training \nprior to professional examination and registration.\n\nJob Scope: Design Architect, Project Architect, \n           Interior Architect\n\nRelevant Courses: Master in Architecture (M Arch), \n                  MBA\n");
        jScrollPane9.setViewportView(jTextArea9);

        jPanel11.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 420, 300));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel1");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane2.addTab("Bachelor of Architecture", jPanel11);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea10.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea10.setRows(5);
        jTextArea10.setText("Career Counsellor\nThis job involves assisting and helping students towards their career choices and decisions. \nCareer Counsellors can be employed with educational institutes, training centers or become \nself-employed.\n\nCopywriter\nA copywriter devises script for television commercials, movies, jingles, slogans or text for \nbrochures etc. Copywriters work with creative team of ad agencies, film productions and media \norganizations.\n\nEvent Planners\nAn event planner organizes events, meetings, exhibitions, wedding ceremonies etc in accordance\nwith client requirements.\n\nRetail Manager\nWith opportunities increasing manifold in organized retail sector comprising branded outlets, \ndepartmental stores and shopping malls, Retail Managers deal with procurement, display and \nother support functions to boost footfalls, sales and increase profit.\n\nTeacher\nCandidates with high academic competence and good communication skills can choose teaching \nprofession. Employment opportunities are available in government/private schools as well as \ncoaching institutes and tuition centers.\n");
        jScrollPane10.setViewportView(jTextArea10);

        jPanel12.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 780, 310));

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel1");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 825, 431));

        jTabbedPane2.addTab("Become Professional", jPanel12);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 410));

        jTabbedPane1.addTab("Arts", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 410));

        jRadioButton2.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Homepage");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Sign Out");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (1).jpg"))); // NOI18N
        jLabel33.setText("jLabel5");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 830, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        Mainpage hm=new Mainpage();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        Homepage mp=new Homepage();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Twelfth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Twelfth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Twelfth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Twelfth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Twelfth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JTextArea jTextArea31;
    private javax.swing.JTextArea jTextArea32;
    private javax.swing.JTextArea jTextArea33;
    private javax.swing.JTextArea jTextArea34;
    private javax.swing.JTextArea jTextArea35;
    private javax.swing.JTextArea jTextArea36;
    private javax.swing.JTextArea jTextArea37;
    private javax.swing.JTextArea jTextArea38;
    private javax.swing.JTextArea jTextArea39;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
